# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "D:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "D:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:/Gelis/Programs/3D model viewer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:/Gelis/Programs/3D model viewer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"D:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"D:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:/Gelis/Programs/3D model viewer/CMakeFiles" "C:/Gelis/Programs/3D model viewer//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:/Gelis/Programs/3D model viewer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

include/imgui/imgui.obj: include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.obj

# target to build an object file
include/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui.cpp.obj
.PHONY : include/imgui/imgui.cpp.obj

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.obj: include/imgui/imgui_demo.cpp.obj
.PHONY : include/imgui/imgui_demo.obj

# target to build an object file
include/imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_demo.cpp.obj
.PHONY : include/imgui/imgui_demo.cpp.obj

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.obj: include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.obj

# target to build an object file
include/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_draw.cpp.obj
.PHONY : include/imgui/imgui_draw.cpp.obj

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_impl_glfw.obj: include/imgui/imgui_impl_glfw.cpp.obj
.PHONY : include/imgui/imgui_impl_glfw.obj

# target to build an object file
include/imgui/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_impl_glfw.cpp.obj
.PHONY : include/imgui/imgui_impl_glfw.cpp.obj

include/imgui/imgui_impl_glfw.i: include/imgui/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/imgui_impl_glfw.i

# target to preprocess a source file
include/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/imgui_impl_glfw.cpp.i

include/imgui/imgui_impl_glfw.s: include/imgui/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
include/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/imgui_impl_glfw.cpp.s

include/imgui/imgui_impl_opengl3.obj: include/imgui/imgui_impl_opengl3.cpp.obj
.PHONY : include/imgui/imgui_impl_opengl3.obj

# target to build an object file
include/imgui/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_impl_opengl3.cpp.obj
.PHONY : include/imgui/imgui_impl_opengl3.cpp.obj

include/imgui/imgui_impl_opengl3.i: include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/imgui_impl_opengl3.cpp.i

include/imgui/imgui_impl_opengl3.s: include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/imgui_impl_opengl3.cpp.s

include/imgui/imgui_stdlib.obj: include/imgui/imgui_stdlib.cpp.obj
.PHONY : include/imgui/imgui_stdlib.obj

# target to build an object file
include/imgui/imgui_stdlib.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_stdlib.cpp.obj
.PHONY : include/imgui/imgui_stdlib.cpp.obj

include/imgui/imgui_stdlib.i: include/imgui/imgui_stdlib.cpp.i
.PHONY : include/imgui/imgui_stdlib.i

# target to preprocess a source file
include/imgui/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_stdlib.cpp.i
.PHONY : include/imgui/imgui_stdlib.cpp.i

include/imgui/imgui_stdlib.s: include/imgui/imgui_stdlib.cpp.s
.PHONY : include/imgui/imgui_stdlib.s

# target to generate assembly for a file
include/imgui/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_stdlib.cpp.s
.PHONY : include/imgui/imgui_stdlib.cpp.s

include/imgui/imgui_tables.obj: include/imgui/imgui_tables.cpp.obj
.PHONY : include/imgui/imgui_tables.obj

# target to build an object file
include/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_tables.cpp.obj
.PHONY : include/imgui/imgui_tables.cpp.obj

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.obj: include/imgui/imgui_widgets.cpp.obj
.PHONY : include/imgui/imgui_widgets.obj

# target to build an object file
include/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_widgets.cpp.obj
.PHONY : include/imgui/imgui_widgets.cpp.obj

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/Camera.obj: src/Camera.cpp.obj
.PHONY : src/Camera.obj

# target to build an object file
src/Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Camera.cpp.obj
.PHONY : src/Camera.cpp.obj

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Editor/Editor.obj: src/Editor/Editor.cpp.obj
.PHONY : src/Editor/Editor.obj

# target to build an object file
src/Editor/Editor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Editor/Editor.cpp.obj
.PHONY : src/Editor/Editor.cpp.obj

src/Editor/Editor.i: src/Editor/Editor.cpp.i
.PHONY : src/Editor/Editor.i

# target to preprocess a source file
src/Editor/Editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Editor/Editor.cpp.i
.PHONY : src/Editor/Editor.cpp.i

src/Editor/Editor.s: src/Editor/Editor.cpp.s
.PHONY : src/Editor/Editor.s

# target to generate assembly for a file
src/Editor/Editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Editor/Editor.cpp.s
.PHONY : src/Editor/Editor.cpp.s

src/GlAbst/Framebuffer.obj: src/GlAbst/Framebuffer.cpp.obj
.PHONY : src/GlAbst/Framebuffer.obj

# target to build an object file
src/GlAbst/Framebuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Framebuffer.cpp.obj
.PHONY : src/GlAbst/Framebuffer.cpp.obj

src/GlAbst/Framebuffer.i: src/GlAbst/Framebuffer.cpp.i
.PHONY : src/GlAbst/Framebuffer.i

# target to preprocess a source file
src/GlAbst/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Framebuffer.cpp.i
.PHONY : src/GlAbst/Framebuffer.cpp.i

src/GlAbst/Framebuffer.s: src/GlAbst/Framebuffer.cpp.s
.PHONY : src/GlAbst/Framebuffer.s

# target to generate assembly for a file
src/GlAbst/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Framebuffer.cpp.s
.PHONY : src/GlAbst/Framebuffer.cpp.s

src/GlAbst/Shader.obj: src/GlAbst/Shader.cpp.obj
.PHONY : src/GlAbst/Shader.obj

# target to build an object file
src/GlAbst/Shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Shader.cpp.obj
.PHONY : src/GlAbst/Shader.cpp.obj

src/GlAbst/Shader.i: src/GlAbst/Shader.cpp.i
.PHONY : src/GlAbst/Shader.i

# target to preprocess a source file
src/GlAbst/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Shader.cpp.i
.PHONY : src/GlAbst/Shader.cpp.i

src/GlAbst/Shader.s: src/GlAbst/Shader.cpp.s
.PHONY : src/GlAbst/Shader.s

# target to generate assembly for a file
src/GlAbst/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Shader.cpp.s
.PHONY : src/GlAbst/Shader.cpp.s

src/GlAbst/Texture.obj: src/GlAbst/Texture.cpp.obj
.PHONY : src/GlAbst/Texture.obj

# target to build an object file
src/GlAbst/Texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Texture.cpp.obj
.PHONY : src/GlAbst/Texture.cpp.obj

src/GlAbst/Texture.i: src/GlAbst/Texture.cpp.i
.PHONY : src/GlAbst/Texture.i

# target to preprocess a source file
src/GlAbst/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Texture.cpp.i
.PHONY : src/GlAbst/Texture.cpp.i

src/GlAbst/Texture.s: src/GlAbst/Texture.cpp.s
.PHONY : src/GlAbst/Texture.s

# target to generate assembly for a file
src/GlAbst/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/Texture.cpp.s
.PHONY : src/GlAbst/Texture.cpp.s

src/GlAbst/VertexPackage.obj: src/GlAbst/VertexPackage.cpp.obj
.PHONY : src/GlAbst/VertexPackage.obj

# target to build an object file
src/GlAbst/VertexPackage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/VertexPackage.cpp.obj
.PHONY : src/GlAbst/VertexPackage.cpp.obj

src/GlAbst/VertexPackage.i: src/GlAbst/VertexPackage.cpp.i
.PHONY : src/GlAbst/VertexPackage.i

# target to preprocess a source file
src/GlAbst/VertexPackage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/VertexPackage.cpp.i
.PHONY : src/GlAbst/VertexPackage.cpp.i

src/GlAbst/VertexPackage.s: src/GlAbst/VertexPackage.cpp.s
.PHONY : src/GlAbst/VertexPackage.s

# target to generate assembly for a file
src/GlAbst/VertexPackage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/GlAbst/VertexPackage.cpp.s
.PHONY : src/GlAbst/VertexPackage.cpp.s

src/Light.obj: src/Light.cpp.obj
.PHONY : src/Light.obj

# target to build an object file
src/Light.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Light.cpp.obj
.PHONY : src/Light.cpp.obj

src/Light.i: src/Light.cpp.i
.PHONY : src/Light.i

# target to preprocess a source file
src/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Light.cpp.i
.PHONY : src/Light.cpp.i

src/Light.s: src/Light.cpp.s
.PHONY : src/Light.s

# target to generate assembly for a file
src/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Light.cpp.s
.PHONY : src/Light.cpp.s

src/Material.obj: src/Material.cpp.obj
.PHONY : src/Material.obj

# target to build an object file
src/Material.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Material.cpp.obj
.PHONY : src/Material.cpp.obj

src/Material.i: src/Material.cpp.i
.PHONY : src/Material.i

# target to preprocess a source file
src/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Material.cpp.i
.PHONY : src/Material.cpp.i

src/Material.s: src/Material.cpp.s
.PHONY : src/Material.s

# target to generate assembly for a file
src/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Material.cpp.s
.PHONY : src/Material.cpp.s

src/Mesh.obj: src/Mesh.cpp.obj
.PHONY : src/Mesh.obj

# target to build an object file
src/Mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Mesh.cpp.obj
.PHONY : src/Mesh.cpp.obj

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Model.obj: src/Model.cpp.obj
.PHONY : src/Model.obj

# target to build an object file
src/Model.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Model.cpp.obj
.PHONY : src/Model.cpp.obj

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Scenes.obj: src/Scenes.cpp.obj
.PHONY : src/Scenes.obj

# target to build an object file
src/Scenes.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Scenes.cpp.obj
.PHONY : src/Scenes.cpp.obj

src/Scenes.i: src/Scenes.cpp.i
.PHONY : src/Scenes.i

# target to preprocess a source file
src/Scenes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Scenes.cpp.i
.PHONY : src/Scenes.cpp.i

src/Scenes.s: src/Scenes.cpp.s
.PHONY : src/Scenes.s

# target to generate assembly for a file
src/Scenes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/Scenes.cpp.s
.PHONY : src/Scenes.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Test"
	@echo "... include/imgui/imgui.obj"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.obj"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.obj"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_impl_glfw.obj"
	@echo "... include/imgui/imgui_impl_glfw.i"
	@echo "... include/imgui/imgui_impl_glfw.s"
	@echo "... include/imgui/imgui_impl_opengl3.obj"
	@echo "... include/imgui/imgui_impl_opengl3.i"
	@echo "... include/imgui/imgui_impl_opengl3.s"
	@echo "... include/imgui/imgui_stdlib.obj"
	@echo "... include/imgui/imgui_stdlib.i"
	@echo "... include/imgui/imgui_stdlib.s"
	@echo "... include/imgui/imgui_tables.obj"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.obj"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/Camera.obj"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Editor/Editor.obj"
	@echo "... src/Editor/Editor.i"
	@echo "... src/Editor/Editor.s"
	@echo "... src/GlAbst/Framebuffer.obj"
	@echo "... src/GlAbst/Framebuffer.i"
	@echo "... src/GlAbst/Framebuffer.s"
	@echo "... src/GlAbst/Shader.obj"
	@echo "... src/GlAbst/Shader.i"
	@echo "... src/GlAbst/Shader.s"
	@echo "... src/GlAbst/Texture.obj"
	@echo "... src/GlAbst/Texture.i"
	@echo "... src/GlAbst/Texture.s"
	@echo "... src/GlAbst/VertexPackage.obj"
	@echo "... src/GlAbst/VertexPackage.i"
	@echo "... src/GlAbst/VertexPackage.s"
	@echo "... src/Light.obj"
	@echo "... src/Light.i"
	@echo "... src/Light.s"
	@echo "... src/Material.obj"
	@echo "... src/Material.i"
	@echo "... src/Material.s"
	@echo "... src/Mesh.obj"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Model.obj"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Scenes.obj"
	@echo "... src/Scenes.i"
	@echo "... src/Scenes.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

